### ISSUE TITLE
Consider Need of Created On and Modified On

### ISSUE THREAD

**Issue by anmolg** [Get-Hale/hale-aws#36]
Need of created on and modified on attributes? 

Currently in trainer profile

**Comment by anmolg** [comment]
created_on / modified_on strictly for auditing / tracking purposes. If client needs it, need to consider adding another attribute for the client

**Comment by ELCHILEN0** [comment]
There is a use case such as client wanting to verify if data has been updated. e.g. current.modified_on > last.modified_on

**Comment by anmolg** [comment]
Let's keep those fields strictly for audit/data analytics. If there is a business case, we can add it as an additional attribute
