### ISSUE TITLE
Incorrect DBName is config.js

### ISSUE THREAD

**Issue by shreyansjain** [Get-Hale/hale-aws#78]
https://github.com/Get-Hale/hale-aws/blob/master/config.js#L12

**Comment by anmolg** [comment]
@shreyansjain - is this really an issue? Seems like connection is fine?

**Comment by shreyansjain** [comment]
Not an issue, but when I was reading the config file to create the connection to the DB, ran into the issue.

More or less, it seems like a typo, should be easy to fix?

via BlackBerry Passport
